# Set a unique name to find it easily
CONFIG_ZMK_KEYBOARD_NAME="Tcherta"


# Basic configuration
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_USB=y

# Make it report the lowest half battery status
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Bluetooth configuration
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y      # for stronger BT signal
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=30000

# These to help halves find each other quicker...
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=30
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# Debounce settings (helps with contacts jitter)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Fighting the flickering pin P0.11 problem
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_USB_LOGGING=n
CONFIG_SERIAL=n
CONFIG_UART_INTERRUPT_DRIVEN=n
